name = "BelTree"
description = "A clean and elegant Linktree alternative that offers customizable links and a user-friendly design"
license = "MIT"
homepage = "https://github.com/cx48/BelTree"
min_version = "0.20.0"

# Live demo URL
demo = "https://cx48.github.io/BelTree"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "cx48"
homepage = "https://cx48.dev"
